namespace MedArchon.Common.Commands.Bus
{
    public enum ValidationField
    {
        LetterId,
        LetterType,
        RacContractor,
        RacPointOfContact,
        RacAddress,
        RacFaxNumber,
        ProviderName,
        ProviderNpi,
        IssueType,
        ErrorAndRegulationRulesReferences,
        DocumentsRequested,
        BeneficiaryFirstName,
        BeneficiaryLastName,
        BeneficiaryHic,
        BeneficiaryDob,
        MedicalRecordNumber,
        PatientControlNumber,
        DosTo,
        DosFrom,
        ClaimNumber,
        MedicarePaymentAmount,
        RacCaseId,
        ErrorType,
        DRG,
        ICDs,
        CaseId,
        AuthenticationToken,
        DocumentType,
        FileName
    }
}